[project]
authors = ["Jermiah <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "med-image_test-data"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
csvs = "bash ./scripts/make_csvs.sh"
tag = "bash ./scripts/tag.sh"

[dependencies]
python = ">=3.13.1,<3.14"
pandas = ">=2.2.3,<3"
