[project]
authors = ["Jermiah <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "med-image_test-data"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
tag = { cmd = "bash ./scripts/tag.sh", description = "Tags the current branch and pushes it to Github, setting off the release job. Only works on main branch and should only be run if pipeline is successful." }
snake = { cmd = "snakemake  --show-failed-logs --printshellcmds --rerun-incomplete", description = "Run the snakemake pipeline" }
clean = { cmd = "rm -rf .snakemake rawdata procdata logs", description = "Clean up the project directory" }

[dependencies]
python = ">=3.12,<3.13"
pandas = ">=2.2.3,<3"
pydantic-settings = ">=2.7.1,<3"
pyyaml = ">=6.0.2,<7"
# ipython = "*"
# jupyter = "*"
rich = ">=13.9.4,<14"
pigz = ">=2.8,<3"
snakemake = ">=8.27.1,<9"

# ruff = "*"

[pypi-dependencies]
nbia-toolkit = { git = "https://github.com/jjjermiah/nbia-toolkit.git", branch = "jjjermiah/2.0" }
tcia_utils = "*"
