[project]
authors = ["Jermiah <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "med-image_test-data"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
csvs = "bash ./scripts/make_csvs.sh"
tag = "bash ./scripts/tag.sh"
snake = "snakemake"

[dependencies]
python = ">=3.12,<3.13"
pandas = ">=2.2.3,<3"
pydantic-settings = ">=2.7.1,<3"
pyyaml = ">=6.0.2,<7"
ipython = "*"
jupyter = "*"
rich = ">=13.9.4,<14"
python-dotenv = ">=1.0.1,<2"
pigz = ">=2.8,<3"
snakemake = ">=8.27.1,<9"

[pypi-dependencies]
nbia-toolkit = { git = "https://github.com/jjjermiah/nbia-toolkit.git", rev = "a0206b1b2e39a0a4fe157434acdbdee1c623c276" }
tcia_utils = "*"
