name: Release Data

on:
  push:
    branches:
      - main
      - "*"
    tags:
      - "v*.*"

permissions:
  contents: write

jobs:
  Run-Pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      NBIA_USERNAME: ${{ secrets.NBIA_USERNAME }}
      NBIA_PASSWORD: ${{ secrets.NBIA_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Display environment variables
        run: |
          echo "NBIA_USERNAME is $NBIA_USERNAME"
          if [ -z "$NBIA_PASSWORD" ]; then
            echo "NBIA_PASSWORD is not set"
          else
            echo "NBIA_PASSWORD is set"
          fi

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: "default"
          pixi-version: v0.40.0
          cache: true
          locked: false

      - name: Run Snakemake
        run: |
          pixi run snake

      # - name: Combine Markdown files
      #   run: |
      #     # Combine all Markdown files into one with a newline after each file's content
      #     combined_file="results/combined_summary.md"
      #     find results -name "*_summary.md" -exec sh -c 'cat {} && echo ""' \; > "$combined_file"
      #     echo "Combined Markdown written to $combined_file"
      #     cat "$combined_file"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./results/*.tar.gz
          body_path: results/combined_summary.md
          make_latest: true
          # body: |
          #   $(cat results/combined_summary.md)