name: Release Data

# only run on pushes to main or pull requests
on:
  push:
    tags:
      - "v*.*"

permissions:
  contents: write

jobs:
  Run-Pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Consider increasing timeout

    env:
      NBIA_USERNAME: ${{ secrets.NBIA_USERNAME }}
      NBIA_PASSWORD: ${{ secrets.NBIA_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display environment variables
        run: |
          echo "NBIA_USERNAME is $NBIA_USERNAME"
          if [ -z "$NBIA_PASSWORD" ]; then
            echo "NBIA_PASSWORD is not set"
          else
            echo "NBIA_PASSWORD is set"
          fi

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: "default"
          pixi-version: v0.40.0
          cache: true
          locked: false # wont be the same because of the tag

      - name: Run Snakemake
        run: |
          pixi run snake

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./procdata/*.tar.gz
