name: Release Data

# only run on pushes to main or pull requests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  Run-Pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Consider increasing timeout

    steps:
      - uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: "default"
          pixi-version: v0.40.0
          cache: true
          locked: false # wont be the same because of the tag

      - uses: actions/checkout@v3
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: MyReleaseMessage
          workdir: ./test_data
