name: Release Data

# only run on pushes to main or pull requests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

permissions:
  contents: write

jobs:
  Run-Pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Consider increasing timeout

    steps:
      - uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: "default"
          pixi-version: v0.40.0
          cache: true
          locked: false # wont be the same because of the tag

      - name: Release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./test_data/*.csv
