name: Release Data

on:
  push:
    branches:
      - main
      - "*"
    tags:
      - "v*.*"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref == 'refs/heads/main' }}

jobs:
  Run-Pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      NBIA_USERNAME: ${{ secrets.NBIA_USERNAME }}
      NBIA_PASSWORD: ${{ secrets.NBIA_PASSWORD }}
      ACCESS_TYPE: ${{ vars.ACCESS_TYPE }}

    steps:
      - uses: actions/checkout@v4

      - name: Display environment variables
        run: |
          echo "ACCESS_TYPE is $ACCESS_TYPE"

          echo "NBIA_USERNAME is $NBIA_USERNAME"
          if [ -z "$NBIA_PASSWORD" ]; then
            echo "NBIA_PASSWORD is not set"
          else
            echo "NBIA_PASSWORD is set"
          fi

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: "default"
          pixi-version: v0.40.0
          cache: true
          locked: false

      - name: Run Snakemake
        run: |
          pixi run snake

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./results/*.tar.gz
            ./results/combined_metadata.csv
          body_path: results/combined_summary.md
          make_latest: true
